# Generated by Django 5.2.9 on 2025-12-04 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTypeRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(db_index=True, help_text='Unique task type identifier', max_length=50, unique=True)),
                ('handler_class', models.CharField(help_text='Fully qualified class name of the task handler', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this task type does')),
                ('default_timeout', models.IntegerField(default=300, help_text='Default timeout in seconds')),
                ('default_priority', models.IntegerField(default=0, help_text='Default priority for this task type')),
                ('max_concurrent', models.IntegerField(default=1, help_text='Maximum concurrent tasks of this type')),
                ('default_max_retries', models.IntegerField(default=3, help_text='Default maximum retry attempts')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this task type is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'queue_task_type_registry',
                'ordering': ['task_type'],
            },
        ),
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, help_text='Human-readable name of the task', max_length=100)),
                ('task_type', models.CharField(db_index=True, help_text='Task type identifier: video_conversion, pdf_processing, etc.', max_length=50)),
                ('task_params', models.JSONField(default=dict, help_text='Parameters required for task execution')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('retrying', 'Retrying'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current status of the task', max_length=20)),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='Priority level (higher numbers = higher priority)')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retry attempts')),
                ('retry_count', models.IntegerField(default=0, help_text='Current number of retry attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the task was created')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the task started processing', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the task completed (or failed)', null=True)),
                ('delay_until', models.DateTimeField(blank=True, help_text='Delay execution until this time', null=True)),
                ('timeout_seconds', models.IntegerField(blank=True, help_text='Task timeout in seconds', null=True)),
                ('result', models.JSONField(blank=True, help_text='Task execution result', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Detailed error message if task failed', null=True)),
                ('execution_log', models.TextField(blank=True, help_text='Execution log with timestamps', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who initiated this task', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'queue_task_queue',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'created_at'], name='queue_task__status_790be4_idx'), models.Index(fields=['task_type', 'status'], name='queue_task__task_ty_34a131_idx'), models.Index(fields=['user', 'status'], name='queue_task__user_id_1b4924_idx')],
            },
        ),
    ]
