# Generated by Django 5.2.8 on 2025-11-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0002_create_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfconversion',
            name='processor',
            field=models.CharField(blank=True, help_text='Selected processor for the conversion', max_length=50, null=True),
        ),
    ]
