# Generated by Django 5.2.8 on 2025-11-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0003_pdfconversion_processor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfconversion',
            name='comments',
            field=models.CharField(blank=True, help_text='User comments about the conversion', max_length=100, null=True),
        ),
    ]
