# Generated by Django 5.2.8 on 2025-11-24 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0004_pdfconversion_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, rename the existing model to preserve data
        migrations.RenameModel(
            old_name='PDFConversion',
            new_name='FileHeader',
        ),
        # Update the foreign key references
        migrations.AlterField(
            model_name='convertedimage',
            name='pdf_conversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='file_processor.fileheader'),
        ),
        # Update the related_name in the user foreign key
        migrations.AlterField(
            model_name='fileheader',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='file_headers', to=settings.AUTH_USER_MODEL),
        ),
    ]