# Generated by Django 5.2.8 on 2025-11-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0005_fileheader_alter_convertedimage_pdf_conversion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileheader',
            old_name='pdf_file',
            new_name='file_header_filename',
        ),
        migrations.AddField(
            model_name='fileheader',
            name='file_type',
            field=models.CharField(blank=True, help_text='File extension', max_length=10, null=True),
        ),
    ]
