# Generated by Django 5.2.8 on 2025-11-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0006_rename_pdf_file_fileheader_file_header_filename_and_more'),
    ]

    operations = [
        # 重命名模型
        migrations.RenameModel(
            old_name='ConvertedImage',
            new_name='FileDetail',
        ),
        # 重命名字段
        migrations.RenameField(
            model_name='filedetail',
            old_name='image_file',
            new_name='file_detail_filename',
        ),
        migrations.RenameField(
            model_name='filedetail',
            old_name='pdf_conversion',
            new_name='file_header',
        ),
        # 更新外键引用
        migrations.AlterField(
            model_name='analysisresult',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_processor.filedetail'),
        ),
        migrations.AlterField(
            model_name='imageanalysis',
            name='images',
            field=models.ManyToManyField(related_name='analyses', to='file_processor.filedetail'),
        ),
    ]