# Generated by Django 5.2.8 on 2025-11-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0013_change_result_data_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileheader',
            name='log',
            field=models.TextField(blank=True, help_text='Processing log with timestamps and progress', null=True),
        ),
    ]
