# Generated by Django 5.2.8 on 2025-11-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0014_fileheader_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileheader',
            name='log',
        ),
    ]
