# Generated by Django 5.2.8 on 2025-11-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0016_add_log_field_to_fileheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileheader',
            name='log',
            field=models.TextField(blank=True, help_text='Processing log with timestamps and progress information', null=True),
        ),
    ]
