# Generated by Django 5.2.8 on 2025-11-28 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0017_alter_fileheader_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('converted', 'Converted'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_data', models.TextField(blank=True, help_text='Analysis result data', null=True)),
                ('log', models.TextField(blank=True, help_text='Processing log with timestamps and progress information', null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Analysis rating', max_digits=5, null=True)),
                ('prompt', models.TextField(blank=True, help_text='Analysis prompt used', null=True)),
                ('files', models.ManyToManyField(related_name='analyses', to='file_processor.filedetail')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='file_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='file_processor.fileanalysis'),
        ),
        migrations.DeleteModel(
            name='ImageAnalysis',
        ),
    ]
