# Generated by Django 5.2.8 on 2025-11-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0018_fileanalysis_alter_analysisresult_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileanalysis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('converting', 'Converting'), ('processing', 'Processing'), ('converted', 'Converted'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='filedetail',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('converting', 'Converting'), ('processing', 'Processing'), ('converted', 'Converted'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='fileheader',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('converting', 'Converting'), ('processing', 'Processing'), ('converted', 'Converted'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
