# Generated by Django 5.2.8 on 2025-11-28 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0019_alter_fileanalysis_status_alter_filedetail_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileanalysis',
            name='files',
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='analysis_type',
            field=models.CharField(choices=[('single', 'Single File'), ('header', 'Header All File')], default='header', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='api_key_used',
            field=models.CharField(blank=True, help_text='API key used for this call', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='file_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail_analyses', to='file_processor.filedetail'),
        ),
        migrations.AddField(
            model_name='fileanalysis',
            name='file_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_analyses', to='file_processor.fileheader'),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='log',
            field=models.TextField(blank=True, help_text='Processing log with timestamps', null=True),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='result_data',
            field=models.TextField(blank=True, help_text='Dify API response result', null=True),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='fileanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_analyses', to=settings.AUTH_USER_MODEL),
        ),
    ]
