# Generated by Django 5.2.8 on 2025-12-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0021_videoanalysis_videodetectionframe_videofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='conversion_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='conversion_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='conversion_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videofile',
            name='conversion_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('converting', 'Converting'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='videofile',
            name='converted_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/converted/'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='converted_format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videofile',
            name='is_web_compatible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videofile',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/original/'),
        ),
        migrations.AddField(
            model_name='videofile',
            name='original_format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('converting', 'Converting'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
