# Generated by Django 5.2.9 on 2025-12-09 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0023_add_detection_type_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoanalysis',
            name='video_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='file_processor.videofile'),
        ),
    ]
