# Generated by Django 5.2.9 on 2025-12-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_processor', '0024_allow_video_file_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='detection_data',
            field=models.JSONField(default=dict, help_text='Aggregated detection results and statistics'),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='detection_type',
            field=models.CharField(choices=[('barcode', 'Barcode Recognition'), ('phone', 'Phone Detection'), ('box', 'Yellow Box Detection'), ('multi', 'Multi-Type Detection')], default='barcode', help_text='Primary detection type for camera-based analysis', max_length=20),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='processing_time',
            field=models.FloatField(blank=True, help_text='Total processing time in seconds', null=True),
        ),
    ]
