"""
Django settings for prj_file_proceed project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 先加载基础环境变量
load_dotenv(BASE_DIR / '.env')

# 检测是否在Docker环境中
DOCKER_ENV = os.getenv('DOCKER_ENV', 'False').lower() == 'true'

# Load environment variables from .env file
if DOCKER_ENV:
    # Docker环境：优先加载.env.docker
    if os.path.exists(BASE_DIR / '.env.docker'):
        load_dotenv(BASE_DIR / '.env.docker', override=True)
    # 也加载.env作为备选
    if os.path.exists(BASE_DIR / '.env'):
        load_dotenv(BASE_DIR / '.env')
else:
    # 本地开发：只加载.env
    load_dotenv(BASE_DIR / '.env')

# 1. 媒体文件存储路径（上传的 PDF + 生成的 PNG 都存在这里）
# 临时强制使用本地路径，因为图片显示问题
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 实际路径：项目根目录/media/

# 如果确实在Docker环境中，取消注释下面的行并注释上面的行
# if DOCKER_ENV:
#     # Docker环境中的路径
#     MEDIA_ROOT = '/app/media'  # 容器内路径，挂载到本地media目录
# else:
#     # 本地开发环境路径
#     MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 实际路径：项目根目录/media/

MEDIA_URL = '/media/'  # 访问 URL：http://127.0.0.1:8000/media/

# 2. 限制上传文件大小（PDF 不宜过大，建议 50MB 以内）
DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 50  # 50MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 50  # 50MB

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 优先从环境变量获取SECRET_KEY，否则使用默认值
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-pc%(xjpf*043y7)t+kgwl=omd&46%k4j#dv2d8_9_2*j96il0%')

# SECURITY WARNING: don't run with debug turned on in production!
# 优先从环境变量获取DEBUG设置，否则使用默认值
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# 允许的主机列表，从环境变量获取或使用默认值
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'file_processor',
    'file_processor.queue',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'prj_file_proceed.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'prj_file_proceed.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 根据环境设置数据库路径
if DOCKER_ENV:
    # Docker环境中的路径
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': '/app/db.sqlite3',  # 容器内绝对路径
            'OPTIONS': {
                'timeout': 30,
                'check_same_thread': False,  # 允许多线程访问
            },
            'CONN_MAX_AGE': 60,  # 连接持久化60秒
        }
    }
else:
    # 本地开发环境路径
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 30,
                'check_same_thread': False,  # 允许多线程访问
            },
            'CONN_MAX_AGE': 60,  # 连接持久化60秒
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us' 

# Use Beijing time (Asia/Shanghai)
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Dify API Configuration（从环境变量获取）
DIFY_API_KEY = os.getenv("DIFY_API_KEY")
DIFY_USER = os.getenv("DIFY_USER")
DIFY_SERVER = os.getenv("DIFY_SERVER")
DIFY_TIMEOUT = os.getenv("DIFY_TIMEOUT", "300")  # 默认300秒超时

DIFY_API_KEY_INVICE_FILES = os.getenv("DIFY_API_KEY_INVICE_FILES")

# Login/Logout redirect URLs
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/auth/login/'

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'file_processor': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'file_processor.video': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
